# Generated by Django 3.1.4 on 2020-12-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('x_coor', models.IntegerField()),
                ('y_coor', models.IntegerField()),
            ],
        ),
    ]
